sudo: required
services:
  - docker

before_install:
  # decrupt gcp service-account.json
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
