sudo: required
services:
  - docker

env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Decrypt GCP service-account.json
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Install GCP CLI
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc

  - gcloud components update kubectl
  # Login to GCP using the file that Travis-ci unencrypted when building the project
  - gcloud auth activate-service-account --key-file=service-account.json
  # Config gcloud cli
  - gcloud config set project kuber-multi
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials cluster-1
  # Login to Docker Hub
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
