name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set GIT_SHA environment variable
        run: echo "GIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Decrypt GCP service account file
        # Ensure you add the encrypted key and IV as GitHub secrets (e.g. ENCRYPTED_9F3B5599B056_KEY and ENCRYPTED_9F3B5599B056_IV)
        run: |
          openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_9F3B5599B056_KEY }} -iv ${{ secrets.ENCRYPTED_9F3B5599B056_IV }} -in service-account.json.enc -out service-account.json -d

      - name: Install Google Cloud SDK and update kubectl
        run: |
          curl https://sdk.cloud.google.com | bash > /dev/null
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components update kubectl
        shell: bash

      - name: Authenticate with GCP and configure CLI
        run: |
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud auth activate-service-account --key-file=service-account.json
          gcloud config set project kuber-multi
          gcloud config set compute/zone us-central1-c
          gcloud container clusters get-credentials cluster-1
        shell: bash

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy application
        run: bash ./deploy.sh
